import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import { Providers } from "./providers";
import "./globals.css";
import Navbar from "@/components/header/Navbar";
import Hero from "@/components/header/hero/Hero";
import Footer from "@/components/footer/Footer";
import React from "react";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";

const poppins = Poppins({
  weight: ["500"],
  subsets: ["latin"],
  display: "auto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Providers>
        <head />
        <body
          className={`${poppins.className} min-h-screen bg-[#eff1f5] dark:bg-[#0d1117]`}
        >
          <NextTopLoader />
          <Navbar />
          <Hero />
          {children}
          <Analytics />
          <SpeedInsights />
          <Footer />
        </body>
      </Providers>
    </html>
  );
}
