import { DocItem } from "@/components/docs/sidebar/types";

export const docsStructure: DocItem[] = [
  {
    title: "EternalCore",
    path: "/docs/eternalcore",
    children: [
      { title: "Introduction", path: "/docs/eternalcore/introduction" },
      {
        title: "Installation and Upgrading",
        path: "/docs/eternalcore/installation",
      },
      {
        title: "Features",
        path: "/docs/eternalcore/features",
        children: [
          { title: "All Commands and Permissions", path: "/docs/eternalcore/features/permissions" },
          { title: "AdminChat", path: "/docs/eternalcore/features/adminchat" },
          { title: "AFK", path: "/docs/eternalcore/features/afk" },
          { title: "Burn", path: "/docs/eternalcore/features/burn" },
          { title: "Butcher", path: "/docs/eternalcore/features/butcher" },
          { title: "Clear inventory", path: "/docs/eternalcore/features/clear" },
          { title: "Container inventories", path: "/docs/eternalcore/features/container" },
          {
            title: "Fun Commands",
            path: "docs/eternalcore/features/fun",
            children: [
              { title: "Elder Guardian", path: "/docs/eternalcore/features/elderguardian" },
            ],
          },
          { title: "Feed", path: "/docs/eternalcore/features/feed" },
          { title: "Fireball", path: "/docs/eternalcore/features/fireball" },
          { title: "Fly", path: "/docs/eternalcore/features/fly" },
          { title: "Freeze", path: "/docs/eternalcore/features/freeze" },
          { title: "Gamemode", path: "/docs/eternalcore/features/gamemode" },
          { title: "Give", path: "/docs/eternalcore/features/give" },
          { title: "God mode", path: "/docs/eternalcore/features/god" },
          { title: "Hat", path: "/docs/eternalcore/features/hat" },
          { title: "Heal", path: "/docs/eternalcore/features/heal" },
          { title: "Homes", path: "/docs/eternalcore/features/homes" },
          { title: "Ignore", path: "/docs/eternalcore/features/ignore" },
          { title: "Item edit", path: "/docs/eternalcore/features/itemedit" },
          { title: "Jail", path: "/docs/eternalcore/features/jail" },
          { title: "Lightning", path: "/docs/eternalcore/features/lightning" },
          { title: "Message of the Day", path: "/docs/eternalcore/features/motd" },
          { title: "Near", path: "/docs/eternalcore/features/near" },
          { title: "Playtime", path: "/docs/eternalcore/features/playtime" },
          { title: "Powertools", path: "/docs/eternalcore/features/powertool" },
          { title: "Private messages", path: "/docs/eternalcore/features/msg" },
          { title: "Random teleport", path: "/docs/eternalcore/features/randomtp" },
          { title: "Repair", path: "/docs/eternalcore/features/repair" },
          { title: "Seen", path: "/docs/eternalcore/features/seen" },
          { title: "Set slot", path: "/docs/eternalcore/features/setslot" },
          { title: "Spawn", path: "/docs/eternalcore/features/spawn" },
          { title: "Speed", path: "/docs/eternalcore/features/speed" },
          { title: "Teleport ask-here", path: "/docs/eternalcore/features/tpahere" },
          { title: "Time", path: "/docs/eternalcore/features/time" },
        ],
      },
      { title: "FAQ", path: "/docs/eternalcore/faq" },
      { title: "Placeholders", path: "/docs/eternalcore/placeholders" },
      { title: "Developer API", path: "/docs/eternalcore/using-api" },
    ],
  },
  {
    title: "EternalCombat",
    path: "/docs/eternalcombat",
    children: [
      { title: "Introduction", path: "/docs/eternalcombat/introduction" },
      {
        title: "Installation and Upgrading",
        path: "/docs/eternalcombat/installation",
      },
      { title: "Features", path: "/docs/eternalcombat/features" },
      { title: "Using API", path: "/docs/eternalcombat/using-api" },
    ],
  },
  {
    title: "Contribute",
    path: "/docs/contribute",
    children: [{ title: "How to Contribute", path: "/docs/contribute/guide" }],
  },
  {
    title: "Notifications",
    path: "/docs/notification",
    children: [{ title: "How to use Notifications?", path: "/docs/notification/notifications" }],
  },
];
